# Generated by Django 4.1.7 on 2023-03-15 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('varda', '0078_alter_aikaleima_avain'),
    ]

    operations = [
        migrations.AddField(
            model_name='z3_additionalcasuserfields',
            name='all_groups',
            field=models.ManyToManyField(blank=True, related_name='additional_cas_user', to='auth.group'),
        ),
        migrations.CreateModel(
            name='Z12_DataAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('henkilo_id', models.IntegerField()),
                ('henkilo_oid', models.CharField(max_length=50, validators=[varda.validators.validate_henkilo_oid])),
                ('access_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('organisaatio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_access_logs', to='varda.organisaatio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data access logs',
            },
        ),
        migrations.AddIndex(
            model_name='z12_dataaccesslog',
            index=models.Index(fields=['timestamp'], name='varda_z12_d_timesta_b07311_idx'),
        ),
    ]
