# Generated by Django 4.0.5 on 2022-06-30 12:13

from django.db import migrations, models
import varda.validators


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0075_batcherror_henkilo_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltyontekija',
            name='sahkopostiosoite',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[varda.validators.validate_email]),
        ),
        migrations.AddField(
            model_name='tyontekija',
            name='sahkopostiosoite',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[varda.validators.validate_email]),
        ),
    ]
